### ISSUE TITLE
[BUG] Download link 

### ISSUE THREAD

**Issue by danidemis** [LightDestory/qBittorrent-Search-Plugins#13]
Hi, 

I am writing to you because I noticed that the plugin works fine in the search but when proceeding with the download it does not show the magnet link as I assume it should, but rather the link to the torrent page (on the engine where the resource is located). As a result, every time I need to open the link, search for the magnet, copy it and manually insert it into the qBittorrent page.

I am using a version of qBittorrent that runs on docker, to be precise I use the _dyonr/qbittorrentvpn_ image. I haven't tried the plugin on a local qBittorrent installation, but maybe you can help me understand why it doesn't.

**Your Environment**
- **qBittorrent's Version:** 4.5.0
- **Python's Version:** Custom / docker image gived
- **Plugin's name and version:** ilcorsaronero/1337x

**Comment by LightDestory** [comment]
I am confused because on my end it works as it should. 

You are probably confusing the "desc_link" property with the "link" property of the torrent's structure. The "desc_link" is the link to the torrent's page as you said, it can be used by "right-click" the torrent record on the search list and clicking on "description link".
The "link" property is used to retrieve directly the torrent file or magnetic link and it is used when you double left click a torrent record on the search list.

For ilcorsaronero implementation, it direcly look for the magnetic link, so it is a bit slow to retrieve metadatas.

**Comment by LightDestory** [comment]
Closing this issue as same of #14 , please track the progress there.

Thanks for the report.
