### ISSUE TITLE
[BUG] TorrentDownload

### ISSUE THREAD

**Issue by Ale4224** [LightDestory/qBittorrent-Search-Plugins#22]
Some plugins, for example torrentdownload, does not get the magnet link right. Instead it gives an https link of the page, sometimes urlencoded

**Your Environment**
- **qBittorrent's Version:**  v4.5.2 Web UI (64-bit)
- **Python's Version:** qBittorrent Suggested
- **Plugin's name and version:** TorrentDownload 1.0

**Comment by LightDestory** [comment]
I think that this issue can be related to: https://github.com/qbittorrent/search-plugins/issues/229 and https://github.com/qbittorrent/qBittorrent/issues/18334

I will try the suggested tips and update as soon as I can.

**Comment by LightDestory** [comment]
The issue is still present but I implemented a workaround for all still workable plugins. 

9eaff49c4499b64b5c098e89ab00717fd2c0b892 should address TorrentDownload. Please test it and report.

This issue is related to TorrentDownload, if there are still other broken plugins please open an issue accordly.

Regards, LightDestory
