### ISSUE TITLE
[BUG] AcademicTorrents not precise

### ISSUE THREAD

**Issue by Pocokk** [LightDestory/qBittorrent-Search-Plugins#24]
**Describe the bug**
When I search for a name, AcademicTorrents lists a bunch of unrelated results, see the picture below. 

Can it be "smarten up" a little?

**Your Environment**
- **qBittorrent's Version:** v4.6.2 64-bit
- **Python's Version:** 3.11
- **Plugin's name and version:** AcademicTorrents 1.2

![academictorrents](https://github.com/LightDestory/qBittorrent-Search-Plugins/assets/81096046/15c817a8-6dab-4fdb-81f0-0e9d2a491770)

**Comment by LightDestory** [comment]
My plugins make use of the website search engine itself, it does not implement any logic to alter the results from the source.

If you try to use these keywords on accademictorrent's website you will get unrelated results too.

It is by design to not implement unrelated logic on the plugins.

This is not a bug on my end, you should ask the website's owner to smart up their search engine.

Regards, LightDestory.
