### ISSUE TITLE
[BUG] Academic Torrents 

### ISSUE THREAD

**Issue by sprshb** [LightDestory/qBittorrent-Search-Plugins#9]
**Describe the bug**
AcademicTorrents Plugin doesn't show search query results when entered

**Your Environment**
- **qBittorrent's Version:** v4.4.2
- **Python's Version:** 3.10
- **Plugin's name and version:** AcademicTorrents v1.0

**Comment by LightDestory** [comment]
It seems that AccademicTorrents pulled out the search API.

Reference: https://academictorrents.com/apiv2/

The documentation seems quite old and unupdated: https://academictorrents.com/docs/api.html

**Comment by LightDestory** [comment]
I opened a issue on their repository to get information about this.

https://github.com/academictorrents/academictorrents-docs/issues/29

**Comment by ieee8023** [comment]
Posting a response here too:

The search API was turned off because there was an insane amount of non academic searches which was degrading service.

A scalable approach for us is to download a database feed which is updated daily and then perform a local search.
```https://academictorrents.com/database.xml```

I will update the documentation for the API soon and add more info about this xml feed. Sorry about that.

**Comment by LightDestory** [comment]
@sprshb the plugin has been updated and it works, it is still a unfinished because there is no caching.

The new searching method seems a bit chanky and unreliable (maybe they need to improve it?) I will ask for more information on their repository.

**Comment by LightDestory** [comment]
Closed with 447d2100c41bde7c6c5307f7c0192065b1f1fe46
